import { useState } from 'react';
import {
  Box,
  Input,
  VStack,
  Heading,
  Text,
} from '@chakra-ui/react';

const diseases = [
    { name: "Hipertensão Arterial", description: "Condição caracterizada pela pressão alta persistente nas artérias.", solutions: ["Reduza o consumo de sal.", "Pratique exercícios regularmente.", "Evite o estresse.", "Mantenha uma dieta saudável.", "Consulte um médico regularmente."] },
    { name: "Diabetes Tipo 2", description: "Doença crônica que afeta a forma como o corpo metaboliza a glicose.", solutions: ["Mantenha uma dieta equilibrada e com baixo teor de açúcar.", "Pratique exercícios físicos regularmente.", "Monitore seus níveis de glicose no sangue.", "Use medicamentos conforme prescrito.", "Consulte um endocrinologista para acompanhamento regular."] },
    { name: "Hipertensão", description: "A hipertensão é uma condição médica caracterizada por pressão arterial elevada, que pode levar a sérios problemas de saúde.", solutions: ["Reduza a ingestão de sal na dieta.", "Pratique exercícios físicos regularmente.", "Mantenha um peso saudável.", "Controle o estresse.", "Evite o consumo excessivo de álcool."] },
    { name: "Diabetes Tipo 2", description: "Diabetes Tipo 2 é uma condição crônica que afeta a forma como o corpo metaboliza a glicose.", solutions: ["Monitore regularmente os níveis de glicose no sangue.", "Siga uma dieta balanceada com baixo teor de açúcar.", "Pratique atividades físicas regularmente.", "Mantenha um peso saudável.", "Consulte um médico regularmente para monitoramento."] },
    { name: "Asma", description: "Asma é uma condição crônica que afeta as vias respiratórias nos pulmões, causando dificuldade para respirar.", solutions: ["Evite alérgenos conhecidos e irritantes.", "Use inaladores de forma correta e regular.", "Pratique exercícios respiratórios.", "Mantenha-se longe de ambientes poluídos.", "Mantenha-se hidratado e siga as orientações médicas."] },
    { name: "Enxaqueca", description: "Enxaqueca é uma condição neurológica que pode causar dores de cabeça severas e outros sintomas.", solutions: ["Evite gatilhos conhecidos, como certos alimentos ou estresse.", "Mantenha um diário de enxaqueca para identificar padrões.", "Consulte um médico para medicação preventiva.", "Descanse em um ambiente escuro e silencioso durante uma crise.", "Mantenha uma rotina regular de sono."] },
    { name: "Anemia", description: "A anemia é uma condição em que o corpo não tem glóbulos vermelhos suficientes para transportar oxigênio adequadamente.", solutions: ["Aumente a ingestão de ferro através da dieta ou suplementos.", "Consulte um médico para determinar a causa subjacente.", "Coma alimentos ricos em vitamina C para melhorar a absorção de ferro.", "Evite chá e café durante as refeições, pois podem inibir a absorção de ferro.", "Faça exames regulares para monitorar os níveis de hemoglobina."] },
    { name: "Osteoporose", description: "A osteoporose é uma condição em que os ossos se tornam fracos e quebradiços.", solutions: ["Inclua cálcio e vitamina D na dieta.", "Pratique exercícios de levantamento de peso e resistência.", "Evite fumar e o consumo excessivo de álcool.", "Faça exames de densidade óssea regularmente.", "Consulte um médico sobre medicações que possam fortalecer os ossos."] },
    { name: "Doença de Alzheimer", description: "O Alzheimer é uma doença neurodegenerativa progressiva que afeta a memória e outras funções cognitivas.", solutions: ["Mantenha o cérebro ativo com atividades cognitivas, como leitura e quebra-cabeças.", "Mantenha uma dieta saudável e equilibrada.", "Exercite-se regularmente para melhorar a saúde cerebral.", "Crie uma rotina diária estruturada para o paciente.", "Consulte um médico para tratamento e suporte."] },
    { name: "Artrite", description: "A artrite é uma inflamação das articulações que pode causar dor e rigidez.", solutions: ["Mantenha-se ativo para preservar a mobilidade das articulações.", "Use anti-inflamatórios conforme prescrito pelo médico.", "Aplique calor ou frio nas articulações para aliviar a dor.", "Mantenha um peso saudável para reduzir a pressão nas articulações.", "Consulte um fisioterapeuta para exercícios personalizados."] },
    { name: "Insuficiência Cardíaca", description: "A insuficiência cardíaca é uma condição em que o coração não bombeia sangue de maneira eficiente.", solutions: ["Reduza a ingestão de sal e líquidos conforme orientação médica.", "Monitore o peso diariamente para detectar retenção de líquidos.", "Tome os medicamentos prescritos rigorosamente.", "Pratique atividades físicas leves sob supervisão médica.", "Evite o consumo de álcool e tabaco."] },
    { name: "Doença Renal Crônica", description: "A doença renal crônica é uma condição em que os rins perdem gradualmente a capacidade de funcionar adequadamente.", solutions: ["Controle a pressão arterial e o diabetes para proteger os rins.", "Limite a ingestão de proteínas, sal e potássio na dieta.", "Mantenha-se hidratado, mas siga as orientações médicas sobre a quantidade de líquidos.", "Faça exames regulares de função renal.", "Consulte um nefrologista para acompanhamento especializado."] },
    { name: "Doença de Parkinson", description: "O Parkinson é uma doença neurodegenerativa que afeta o movimento.", solutions: ["Pratique exercícios físicos regulares para manter a mobilidade.", "Use medicamentos conforme prescrito pelo neurologista.", "Adapte o ambiente doméstico para facilitar a mobilidade e segurança.", "Considere terapia ocupacional para melhorar a qualidade de vida.", "Participe de grupos de apoio para compartilhar experiências."] },
    { name: "Depressão", description: "A depressão é um transtorno mental caracterizado por tristeza persistente e perda de interesse.", solutions: ["Busque ajuda de um profissional de saúde mental.", "Mantenha uma rotina de atividades diárias para evitar isolamento.", "Pratique exercícios físicos para liberar endorfinas.", "Converse com amigos ou familiares de confiança sobre seus sentimentos.", "Evite o uso de álcool e drogas como forma de lidar com a depressão."] },
    { name: "Ansiedade", description: "A ansiedade é um transtorno caracterizado por preocupação excessiva e medo.", solutions: ["Pratique técnicas de relaxamento, como respiração profunda e meditação.", "Evite estimulantes como cafeína e nicotina.", "Faça exercícios físicos regulares para reduzir a tensão.", "Busque terapia cognitivo-comportamental (TCC) para ajudar a gerenciar a ansiedade.", "Estabeleça uma rotina de sono regular e relaxante."] },
    { name: "Hipotireoidismo", description: "O hipotireoidismo é uma condição em que a glândula tireoide não produz hormônios suficientes.", solutions: ["Tome os medicamentos prescritos rigorosamente.", "Faça exames de sangue regularmente para monitorar os níveis hormonais.", "Mantenha uma dieta rica em iodo, conforme orientação médica.", "Evite alimentos que possam interferir na função da tireoide, como soja e brócolis.", "Mantenha uma rotina regular de sono e exercício."] },
    { name: "Hiperlipidemia", description: "A hiperlipidemia é uma condição em que há altos níveis de lipídios (gorduras) no sangue.", solutions: ["Reduza a ingestão de gorduras saturadas e trans.", "Inclua mais frutas, vegetais e fibras na dieta.", "Pratique exercícios físicos regularmente para manter níveis saudáveis de colesterol.", "Evite fumar e o consumo excessivo de álcool.", "Tome medicamentos conforme prescrito para controlar os níveis de lipídios."] },
    { name: "Gastrite", description: "A gastrite é a inflamação do revestimento do estômago.", solutions: ["Evite alimentos e bebidas irritantes, como café, álcool e alimentos apimentados.", "Faça refeições menores e mais frequentes.", "Use medicamentos conforme prescrito para reduzir a acidez estomacal.", "Evite o uso prolongado de anti-inflamatórios não esteroides (AINEs).", "Pratique técnicas de relaxamento para reduzir o estresse, que pode piorar a gastrite."] },
    { name: "Refluxo Gastroesofágico", description: "O refluxo gastroesofágico ocorre quando o ácido estomacal retorna ao esôfago, causando desconforto.", solutions: ["Evite alimentos gordurosos, cítricos, chocolate e café.", "Não se deite imediatamente após as refeições.", "Mantenha um peso saudável para reduzir a pressão abdominal.", "Use travesseiros elevados para dormir, para evitar o refluxo noturno.", "Consulte um médico para uso de antiácidos ou outros medicamentos."] },
    { name: "Dermatite Atópica", description: "A dermatite atópica é uma condição crônica da pele que causa inflamação e coceira.", solutions: ["Use hidratantes regularmente para manter a pele hidratada.", "Evite sabonetes e produtos perfumados que possam irritar a pele.", "Use roupas de algodão para evitar irritação.", "Aplique cremes corticosteróides conforme prescrito pelo médico.", "Mantenha as unhas curtas para evitar feridas ao coçar."] },
    { name: "Psoríase", description: "A psoríase é uma condição crônica que causa a aceleração do ciclo de vida das células da pele, resultando em manchas escamosas.", solutions: ["Use cremes e pomadas prescritas para reduzir a inflamação e a escamação.", "Tome banhos de sol moderados para melhorar os sintomas.", "Evite fatores desencadeantes como estresse e tabagismo.", "Use roupas leves e respiráveis para evitar irritação.", "Considere tratamentos com luz UV sob orientação médica."] },
    { name: "Síndrome do Intestino Irritável", description: "A Síndrome do Intestino Irritável (SII) é um distúrbio gastrointestinal que causa dor abdominal, inchaço e alterações nos hábitos intestinais.", solutions: ["Adote uma dieta rica em fibras e evite alimentos desencadeantes.", "Mantenha uma rotina de exercícios físicos.", "Gerencie o estresse através de técnicas de relaxamento.", "Tome probióticos para melhorar a saúde intestinal.", "Consulte um médico para orientação sobre medicamentos e dieta."] },
    { name: "Fibromialgia", description: "A fibromialgia é uma condição que causa dor muscular generalizada e sensibilidade.", solutions: ["Pratique exercícios regulares de baixo impacto, como caminhada ou natação.", "Adote uma rotina de sono regular para melhorar o descanso.", "Use técnicas de relaxamento, como ioga e meditação.", "Considere terapia cognitivo-comportamental (TCC) para lidar com a dor crônica.", "Consulte um médico sobre medicamentos para alívio da dor."] },
    { name: "Anemia Falciforme", description: "A anemia falciforme é uma doença hereditária que afeta a forma dos glóbulos vermelhos, causando dor e danos aos órgãos.", solutions: ["Mantenha-se hidratado para evitar crises de dor.", "Evite temperaturas extremas e exercícios extenuantes.", "Consulte um médico regularmente para monitoramento e tratamento.", "Tome medicamentos conforme prescrito para evitar infecções.", "Considere transfusões de sangue e outros tratamentos conforme necessário."] },
    { name: "Câncer de Mama", description: "O câncer de mama é um tipo de câncer que se forma nas células da mama.", solutions: ["Realize autoexames regulares das mamas.", "Faça mamografias de rotina conforme recomendado pelo médico.", "Mantenha um peso saudável e pratique exercícios regularmente.", "Evite o consumo excessivo de álcool e tabaco.", "Consulte um médico sobre tratamentos disponíveis, como cirurgia, quimioterapia e radioterapia."] },
    { name: "Câncer de Próstata", description: "O câncer de próstata é um tipo de câncer que afeta a próstata, uma glândula do sistema reprodutor masculino.", solutions: ["Faça exames regulares de PSA e toque retal conforme recomendado pelo médico.", "Mantenha uma dieta saudável rica em vegetais e pobre em gorduras saturadas.", "Pratique exercícios regularmente para manter a saúde geral.", "Evite o consumo excessivo de álcool e tabaco.", "Consulte um médico sobre opções de tratamento, como cirurgia, radioterapia e vigilância ativa."] },
    { name: "Câncer de Pulmão", description: "O câncer de pulmão é um tipo de câncer que começa nos pulmões.", solutions: ["Evite o consumo de tabaco e exposição ao fumo passivo.", "Mantenha-se ativo e pratique exercícios regularmente.", "Consulte um médico sobre exames de rastreamento se você estiver em um grupo de risco.", "Evite a exposição a substâncias nocivas no ambiente de trabalho.", "Consulte um oncologista para discutir opções de tratamento, como cirurgia, quimioterapia e imunoterapia."] },
    { name: "Câncer de Pele", description: "O câncer de pele é o crescimento anormal das células da pele, geralmente causado pela exposição ao sol.", solutions: ["Use protetor solar diariamente com um fator de proteção adequado.", "Evite a exposição solar direta durante as horas de pico.", "Use roupas de proteção e chapéus ao se expor ao sol.", "Consulte um dermatologista regularmente para exames de pele.", "Evite o uso de camas de bronzeamento."] },
    { name: "Câncer de Colo do Útero", description: "O câncer de colo do útero é um tipo de câncer que ocorre no colo do útero, a parte inferior do útero.", solutions: ["Faça exames regulares de Papanicolau para detecção precoce.", "Considere a vacinação contra o HPV.", "Mantenha uma dieta saudável e evite o tabagismo.", "Pratique sexo seguro para reduzir o risco de infecção por HPV.", "Consulte um ginecologista sobre tratamentos disponíveis, como cirurgia e radioterapia."] },
    { name: "Lúpus", description: "Lúpus é uma doença autoimune crônica que pode afetar várias partes do corpo.", solutions: ["Use protetor solar para proteger a pele contra erupções cutâneas.", "Mantenha uma dieta saudável e equilibrada.", "Pratique exercícios físicos regularmente para manter a saúde geral.", "Consulte um reumatologista para tratamento especializado.", "Evite o estresse e pratique técnicas de relaxamento."] },
    { name: "Esclerose Múltipla", description: "A esclerose múltipla é uma doença autoimune que afeta o sistema nervoso central.", solutions: ["Pratique exercícios regulares de baixo impacto, como natação ou caminhada.", "Mantenha uma dieta equilibrada rica em ômega-3.", "Consulte um neurologista regularmente para acompanhamento e tratamento.", "Use medicamentos conforme prescrito para gerenciar os sintomas.", "Participe de grupos de apoio para compartilhar experiências e obter suporte."] },
    { name: "Síndrome do Ovário Policístico (SOP)", description: "A Síndrome do Ovário Policístico (SOP) é um distúrbio hormonal comum em mulheres em idade reprodutiva.", solutions: ["Mantenha um peso saudável através de dieta e exercícios.", "Consulte um ginecologista para monitorar os ciclos menstruais.", "Use medicamentos conforme prescrito para regular os hormônios.", "Evite alimentos processados e ricos em açúcar.", "Pratique técnicas de gerenciamento de estresse, como ioga ou meditação."] },
    { name: "Epilepsia", description: "A epilepsia é um distúrbio neurológico que causa crises convulsivas.", solutions: ["Tome os medicamentos antiepilépticos conforme prescrito.", "Evite gatilhos conhecidos que possam causar crises.", "Use uma pulseira de identificação médica para informar outras pessoas sobre a condição.", "Mantenha um diário de crises para monitorar a frequência e os gatilhos.", "Consulte um neurologista regularmente para ajuste do tratamento."] },
    { name: "Doença Celíaca", description: "A doença celíaca é uma condição autoimune em que a ingestão de glúten causa danos ao intestino delgado.", solutions: ["Adote uma dieta sem glúten estritamente.", "Consulte um nutricionista para orientação sobre uma dieta equilibrada sem glúten.", "Evite o consumo de alimentos processados que possam conter glúten oculto.", "Consulte um gastroenterologista para monitoramento e acompanhamento.", "Mantenha-se informado sobre alimentos que podem conter glúten oculto."] },
    { name: "Doença de Crohn", description: "A Doença de Crohn é um tipo de doença inflamatória intestinal que afeta o trato gastrointestinal.", solutions: ["Mantenha uma dieta equilibrada e evite alimentos que possam desencadear sintomas.", "Pratique exercícios regulares para melhorar a saúde geral.", "Use medicamentos conforme prescrito pelo médico.", "Evite o estresse, que pode piorar os sintomas.", "Consulte um gastroenterologista regularmente para monitoramento e tratamento."] },
    { name: "Colite Ulcerativa", description: "A colite ulcerativa é uma doença inflamatória intestinal que causa inflamação crônica no intestino grosso.", solutions: ["Adote uma dieta equilibrada e evite alimentos que possam irritar o intestino.", "Use medicamentos anti-inflamatórios conforme prescrito pelo médico.", "Consulte um gastroenterologista para acompanhamento regular.", "Pratique técnicas de relaxamento para gerenciar o estresse.", "Evite o consumo de álcool e alimentos processados."] },
    { name: "Gota", description: "A gota é uma forma de artrite que causa ataques repentinos e graves de dor, inchaço e vermelhidão nas articulações.", solutions: ["Evite alimentos ricos em purinas, como carnes vermelhas e frutos do mar.", "Beba bastante água para ajudar a eliminar o ácido úrico do corpo.", "Use medicamentos conforme prescrito pelo médico para aliviar a dor e a inflamação.", "Mantenha um peso saudável para reduzir a pressão nas articulações.", "Consulte um reumatologista para acompanhamento e tratamento."] },
    { name: "Síndrome Metabólica", description: "A síndrome metabólica é um grupo de condições que ocorrem juntas, aumentando o risco de doenças cardíacas, derrame e diabetes tipo 2.", solutions: ["Mantenha uma dieta saudável rica em fibras e baixa em gorduras saturadas.", "Pratique exercícios regularmente para manter um peso saudável.", "Monitore regularmente os níveis de açúcar no sangue, pressão arterial e colesterol.", "Evite o consumo de tabaco e álcool.", "Consulte um médico para orientação sobre medicamentos e mudanças no estilo de vida."] },
    { name: "Hipertensão Arterial", description: "A hipertensão arterial, ou pressão alta, é uma condição em que a força do sangue contra as paredes das artérias é alta demais.", solutions: ["Reduza a ingestão de sal na dieta.", "Pratique exercícios regularmente para manter o coração saudável.", "Evite o consumo excessivo de álcool e tabaco.", "Mantenha um peso saudável.", "Monitore a pressão arterial regularmente e consulte um médico para tratamento."] },
    { name: "Hipotensão", description: "A hipotensão é uma condição em que a pressão arterial é anormalmente baixa, o que pode causar tonturas e desmaios.", solutions: ["Aumente a ingestão de líquidos para manter a pressão arterial estável.", "Evite ficar de pé por longos períodos de tempo.", "Consuma pequenas refeições com frequência.", "Use meias de compressão para melhorar a circulação sanguínea.", "Consulte um médico para orientação sobre tratamento e mudanças no estilo de vida."] },
    { name: "Doença de Parkinson", description: "A doença de Parkinson é um distúrbio neurológico progressivo que afeta o movimento.", solutions: ["Pratique exercícios físicos regulares, como caminhada ou natação.", "Use medicamentos conforme prescrito para gerenciar os sintomas.", "Participe de fisioterapia e terapia ocupacional para melhorar a mobilidade.", "Consulte um neurologista para acompanhamento regular.", "Considere participar de grupos de apoio para compartilhar experiências e obter suporte."] },
    { name: "Demência", description: "A demência é um termo geral para um declínio na função mental grave o suficiente para interferir na vida diária.", solutions: ["Mantenha uma dieta saudável e equilibrada rica em antioxidantes.", "Pratique exercícios físicos regularmente para manter a saúde cerebral.", "Mantenha o cérebro ativo através de leitura, jogos e atividades sociais.", "Consulte um neurologista para acompanhamento regular.", "Considere participar de programas de reabilitação cognitiva."] },
    { name: "Esquizofrenia", description: "A esquizofrenia é um transtorno mental grave que afeta a maneira como uma pessoa pensa, sente e se comporta.", solutions: ["Use medicamentos antipsicóticos conforme prescrito pelo psiquiatra.", "Participe de terapia cognitivo-comportamental para gerenciar os sintomas.", "Mantenha uma rotina diária estruturada para ajudar a organizar o dia.", "Evite o uso de substâncias como álcool e drogas recreativas.", "Consulte um psiquiatra regularmente para acompanhamento e ajuste do tratamento."] },
    { name: "Depressão", description: "A depressão é um transtorno de humor que causa uma sensação persistente de tristeza e perda de interesse.", solutions: ["Consulte um psicólogo ou psiquiatra para terapia.", "Pratique exercícios físicos regularmente para melhorar o humor.", "Mantenha uma rotina de sono saudável e evite o consumo de álcool.", "Participe de atividades sociais e hobbies que lhe tragam prazer.", "Use medicamentos antidepressivos conforme prescrito pelo médico."] },
    { name: "Transtorno de Ansiedade Generalizada", description: "O transtorno de ansiedade generalizada (TAG) é uma condição em que a pessoa sente ansiedade persistente e excessiva.", solutions: ["Participe de terapia cognitivo-comportamental para gerenciar a ansiedade.", "Pratique técnicas de relaxamento, como meditação e respiração profunda.", "Mantenha uma rotina de exercícios físicos regulares.", "Evite o consumo de cafeína e outros estimulantes.", "Consulte um médico sobre medicamentos ansiolíticos, se necessário."] },
    { name: "Transtorno Bipolar", description: "O transtorno bipolar é um transtorno de humor caracterizado por episódios de mania e depressão.", solutions: ["Use medicamentos estabilizadores de humor conforme prescrito pelo psiquiatra.", "Participe de terapia cognitivo-comportamental para gerenciar os sintomas.", "Mantenha uma rotina diária estruturada para ajudar a estabilizar o humor.", "Evite o consumo de álcool e drogas recreativas.", "Consulte um psiquiatra regularmente para acompanhamento e ajuste do tratamento."] },
    { name: "Transtorno de Déficit de Atenção e Hiperatividade (TDAH)", description: "O Transtorno de Déficit de Atenção e Hiperatividade (TDAH) é uma condição neurobiológica caracterizada por desatenção, impulsividade e hiperatividade.", solutions: ["Use medicamentos estimulantes conforme prescrito pelo médico.", "Participe de terapia comportamental para desenvolver habilidades de gerenciamento de tempo e organização.", "Mantenha uma rotina diária estruturada e previsível.", "Evite atividades e ambientes que possam causar distrações excessivas.", "Consulte um psicólogo ou psiquiatra para acompanhamento regular."] },
    { name: "Autismo", description: "O autismo é um transtorno do neurodesenvolvimento que afeta a comunicação e o comportamento.", solutions: ["Participe de terapia comportamental para melhorar as habilidades sociais e de comunicação.", "Consulte um psicólogo ou psiquiatra especializado em autismo para orientação.", "Mantenha uma rotina estruturada para ajudar a pessoa a se sentir segura.", "Use técnicas de comunicação visual, como quadros e pictogramas.", "Participe de grupos de apoio para compartilhar experiências e obter suporte."] },
    { name: "Espondilite Anquilosante", description: "A espondilite anquilosante é uma forma de artrite que afeta principalmente a coluna vertebral, causando inflamação e dor.", solutions: ["Pratique exercícios físicos regulares para manter a flexibilidade e força.", "Use medicamentos anti-inflamatórios conforme prescrito pelo médico.", "Participe de fisioterapia para melhorar a postura e mobilidade.", "Evite atividades que possam causar estresse na coluna.", "Consulte um reumatologista para acompanhamento regular."] },
    { name: "Doença de Huntington", description: "A doença de Huntington é uma condição hereditária que causa a degeneração progressiva das células nervosas no cérebro.", solutions: ["Consulte um neurologista para acompanhamento e tratamento.", "Participe de terapia física e ocupacional para manter a mobilidade.", "Use medicamentos conforme prescrito para gerenciar os sintomas.", "Mantenha uma dieta saudável e equilibrada.", "Considere participar de grupos de apoio para compartilhar experiências e obter suporte."] },
    { name: "Osteoporose", description: "A osteoporose é uma condição em que os ossos se tornam fracos e frágeis.", solutions: ["Mantenha uma dieta rica em cálcio e vitamina D.", "Pratique exercícios de fortalecimento ósseo, como caminhada e levantamento de peso.", "Use suplementos de cálcio e vitamina D conforme prescrito pelo médico.", "Evite o consumo de álcool e tabaco.", "Consulte um ortopedista para acompanhamento regular."] },
    { name: "Artrite Reumatoide", description: "A artrite reumatoide é uma doença autoimune que causa inflamação nas articulações.", solutions: ["Use medicamentos anti-inflamatórios e imunossupressores conforme prescrito pelo médico.", "Participe de fisioterapia para melhorar a mobilidade e força.", "Mantenha uma dieta saudável e equilibrada.", "Pratique exercícios físicos regulares de baixo impacto.", "Consulte um reumatologista para acompanhamento regular."] },
    { name: "Insuficiência Renal Crônica", description: "A insuficiência renal crônica é uma condição em que os rins perdem gradualmente a função ao longo do tempo.", solutions: ["Mantenha uma dieta baixa em sódio, potássio e proteínas.", "Monitore regularmente a pressão arterial e os níveis de açúcar no sangue.", "Use medicamentos conforme prescrito pelo médico para controlar os sintomas.", "Evite o consumo de álcool e tabaco.", "Consulte um nefrologista para acompanhamento regular."] },
    { name: "Hepatite B", description: "A hepatite B é uma infecção viral que afeta o fígado.", solutions: ["Use preservativos durante as relações sexuais para evitar a transmissão do vírus.", "Consulte um médico para acompanhamento regular e tratamento.", "Evite o consumo de álcool, que pode piorar o dano hepático.", "Mantenha uma dieta saudável e equilibrada.", "Considere a vacinação contra hepatite B."] },
    { name: "Hepatite C", description: "A hepatite C é uma infecção viral que causa inflamação do fígado.", solutions: ["Evite o compartilhamento de agulhas ou outros itens que possam entrar em contato com sangue.", "Consulte um médico para tratamento e acompanhamento regular.", "Evite o consumo de álcool para reduzir o dano hepático.", "Mantenha uma dieta saudável e equilibrada.", "Consulte um médico sobre novas terapias antivirais para tratamento da hepatite C."] },
    { name: "Cirrose Hepática", description: "A cirrose hepática é uma condição crônica em que o fígado é danificado e forma tecido cicatricial.", solutions: ["Evite o consumo de álcool e tabaco.", "Mantenha uma dieta saudável e equilibrada.", "Use medicamentos conforme prescrito para controlar os sintomas.", "Consulte um hepatologista para acompanhamento regular.", "Considere participar de programas de suporte para lidar com a condição."] },
    { name: "Pneumonia", description: "A pneumonia é uma infecção pulmonar que causa inflamação dos sacos aéreos.", solutions: ["Use antibióticos conforme prescrito pelo médico.", "Descanse bastante e beba muitos líquidos.", "Use um umidificador para manter as vias aéreas úmidas.", "Evite o tabaco e outros irritantes respiratórios.", "Consulte um médico para acompanhamento regular."] },
    { name: "Asma", description: "A asma é uma condição crônica que afeta as vias aéreas e causa dificuldade para respirar.", solutions: ["Use inaladores e outros medicamentos conforme prescrito pelo médico.", "Evite alérgenos e irritantes que possam desencadear crises de asma.", "Mantenha um ambiente limpo e livre de poeira.", "Participe de exercícios de respiração para fortalecer os pulmões.", "Consulte um pneumologista para acompanhamento regular."] },
    { name: "Doença Pulmonar Obstrutiva Crônica (DPOC)", description: "A DPOC é um grupo de doenças pulmonares que causam obstrução das vias aéreas e dificuldades respiratórias.", solutions: ["Use medicamentos broncodilatadores conforme prescrito pelo médico.", "Participe de programas de reabilitação pulmonar para melhorar a capacidade respiratória.", "Evite o tabaco e outros irritantes respiratórios.", "Mantenha uma dieta saudável e equilibrada.", "Consulte um pneumologista para acompanhamento regular."] },
    { name: "Tuberculose", description: "A tuberculose é uma infecção bacteriana que afeta principalmente os pulmões.", solutions: ["Use antibióticos conforme prescrito pelo médico por todo o período indicado.", "Mantenha uma dieta saudável e equilibrada para fortalecer o sistema imunológico.", "Evite o tabaco e outros irritantes respiratórios.", "Descanse bastante e evite o esforço físico durante o tratamento.", "Consulte um médico para acompanhamento regular e monitoramento do tratamento."] },
    { name: "Bronquite Crônica", description: "A bronquite crônica é uma inflamação das vias aéreas que causa tosse persistente e produção de muco.", solutions: ["Evite o tabaco e outros irritantes respiratórios.", "Use medicamentos broncodilatadores conforme prescrito pelo médico.", "Mantenha um ambiente limpo e livre de poeira e outros irritantes.", "Participe de exercícios de respiração para fortalecer os pulmões.", "Consulte um pneumologista para acompanhamento regular."] },
    { name: "Embolia Pulmonar", description: "A embolia pulmonar é uma condição em que um coágulo de sangue bloqueia uma artéria nos pulmões.", solutions: ["Use medicamentos anticoagulantes conforme prescrito pelo médico.", "Evite ficar sentado ou deitado por longos períodos de tempo.", "Pratique exercícios físicos regularmente para melhorar a circulação sanguínea.", "Mantenha um peso saudável.", "Consulte um médico para acompanhamento regular."] },
    { name: "Varizes", description: "As varizes são veias inchadas e torcidas que aparecem geralmente nas pernas e podem causar desconforto.", solutions: ["Evite ficar em pé por longos períodos de tempo.", "Use meias de compressão para melhorar a circulação sanguínea.", "Pratique exercícios físicos regularmente para fortalecer as pernas.", "Mantenha um peso saudável.", "Consulte um angiologista ou cirurgião vascular para acompanhamento e tratamento."] },
    { name: "Apneia do Sono", description: "A apneia do sono é um distúrbio em que a respiração é interrompida repetidamente durante o sono.", solutions: ["Use dispositivos de pressão positiva contínua nas vias aéreas (CPAP) conforme prescrito pelo médico.", "Evite o consumo de álcool e sedativos antes de dormir.", "Mantenha um peso saudável.", "Durma de lado em vez de de costas.", "Consulte um especialista em sono para acompanhamento e tratamento."] },
    { name: "Hernia de Disco", description: "A hérnia de disco ocorre quando um dos discos da coluna vertebral se desloca e pressiona os nervos ao redor.", solutions: ["Pratique exercícios de fortalecimento do core para estabilizar a coluna.", "Evite levantar objetos pesados de forma inadequada.", "Use medicamentos para alívio da dor conforme prescrito pelo médico.", "Participe de fisioterapia para melhorar a mobilidade.", "Consulte um ortopedista para acompanhamento e tratamento."] },
    { name: "Cálculos Renais", description: "Os cálculos renais são depósitos duros de minerais e sais que se formam nos rins.", solutions: ["Beba bastante água para ajudar a eliminar os cálculos.", "Use medicamentos conforme prescrito para aliviar a dor.", "Evite alimentos ricos em oxalato, como espinafre e beterraba.", "Consulte um urologista para tratamento e acompanhamento.", "Considere procedimentos médicos para remoção dos cálculos se necessário."] },
    { name: "Gastrite", description: "A gastrite é uma inflamação do revestimento do estômago, que pode causar dor e desconforto abdominal.", solutions: ["Evite alimentos e bebidas que irritam o estômago, como cafeína, álcool e alimentos picantes.", "Use medicamentos antiácidos ou inibidores da bomba de prótons conforme prescrito pelo médico.", "Mantenha uma dieta equilibrada e evite refeições grandes antes de dormir.", "Evite o uso de anti-inflamatórios não esteroides (AINEs) sem orientação médica.", "Consulte um gastroenterologista para acompanhamento regular."] },
    { name: "Úlcera Péptica", description: "A úlcera péptica é uma ferida no revestimento do estômago ou do intestino delgado.", solutions: ["Use medicamentos para reduzir a produção de ácido no estômago, conforme prescrito pelo médico.", "Evite alimentos que irritam o estômago, como alimentos ácidos e picantes.", "Mantenha uma dieta equilibrada e evite o tabaco e o álcool.", "Consulte um gastroenterologista para acompanhamento e tratamento.", "Considere o teste e tratamento para a bactéria H. pylori se indicado pelo médico."] },
    { name: "Doença de Crohn", description: "A doença de Crohn é uma condição inflamatória crônica do trato gastrointestinal.", solutions: ["Use medicamentos anti-inflamatórios e imunossupressores conforme prescrito pelo médico.", "Mantenha uma dieta equilibrada e evite alimentos que desencadeiem os sintomas.", "Participe de consultas regulares com um gastroenterologista.", "Pratique exercícios regularmente para melhorar o bem-estar geral.", "Considere o suporte de um nutricionista para gerenciamento da dieta."] },
    { name: "Colite Ulcerativa", description: "A colite ulcerativa é uma condição inflamatória crônica que afeta o cólon e o reto.", solutions: ["Use medicamentos anti-inflamatórios conforme prescrito pelo médico.", "Mantenha uma dieta equilibrada e evite alimentos que possam irritar o trato digestivo.", "Participe de consultas regulares com um gastroenterologista.", "Pratique exercícios regularmente para ajudar a gerenciar o estresse.", "Considere a terapia psicológica para ajudar a lidar com a doença."] },
    { name: "Síndrome do Intestino Irritável (SII)", description: "A síndrome do intestino irritável é um distúrbio gastrointestinal que causa dor abdominal, gases e alterações nos hábitos intestinais.", solutions: ["Mantenha uma dieta rica em fibras e evite alimentos que desencadeiem os sintomas.", "Use medicamentos antiespasmódicos conforme prescrito pelo médico.", "Pratique exercícios regularmente para ajudar a reduzir o estresse.", "Considere o suporte de um nutricionista para ajustar a dieta.", "Participe de consultas regulares com um gastroenterologista para acompanhamento."] },
    { name: "Hemorroidas", description: "As hemorroidas são veias inchadas no ânus e no reto inferior que podem causar desconforto e sangramento.", solutions: ["Mantenha uma dieta rica em fibras para prevenir constipação.", "Beba bastante água para ajudar a manter as fezes macias.", "Use pomadas ou supositórios conforme prescrito pelo médico para alívio dos sintomas.", "Evite ficar sentado por longos períodos de tempo.", "Consulte um proctologista para tratamento e acompanhamento."] },
];

const HealthRecommendations = () => {
  const [searchTerm, setSearchTerm] = useState('');

  const filteredDiseases = diseases.filter(disease =>
    disease.name.toLowerCase().includes(searchTerm.toLowerCase())
  );

  return (
    <Box p={5}>
      <Heading mb={4}>Recomendações de Saúde</Heading>
      
      <Input
        placeholder="Pesquisar doença..."
        value={searchTerm}
        onChange={(e) => setSearchTerm(e.target.value)}
        mb={6}
      />

      <VStack align="start" spacing={5}>
        {filteredDiseases.map((disease, index) => (
          <Box key={index} p={5} shadow="md" borderWidth="1px" width="100%">
            <Heading fontSize="xl">{disease.name}</Heading>
            <Text mt={4}>{disease.description}</Text>
            <Text mt={4} fontWeight="bold">Soluções:</Text>
            <VStack align="start" spacing={2} mt={2}>
              {disease.solutions.map((solution, idx) => (
                <Text key={idx}>- {solution}</Text>
              ))}
            </VStack>
          </Box>
        ))}
      </VStack>
    </Box>
  );
};

export default HealthRecommendations;
